@startuml diaSeqEditarResumo
title "Diagrama de Sequência de Edição do Resumo"
hide footbox

actor Pesquisador as user
boundary "Tela do Currículo" as uiRE 
control "Controle do Currículo" as contRE 
entity "Currículo" as res

user -> uiRE ++: Preenche formulario

autonumber
uiRE -> contRE ++: editarResumo()
contRE -->> res **: editResumo()

autonumber stop
res -->> contRE : msgConfirmacao()
contRE -->> uiRE : msgConfirmacao()

@enduml