@startuml DiagramaCadastrarPremio
title "Diagrama de Sequência: Cadastro de Prêmio"
hide footbox

actor "Pesquisador" as Pesquisador
boundary "Tela de Prêmio" as UIPremio
control "Controle de Prêmio" as ControlePremio
entity "Prêmio" as Premio

Pesquisador --> UIPremio ++: Solicita o cadastro

autonumber
UIPremio -> ControlePremio ++: cadPremio(premio)

group Enquanto os dados forem inválidos
ControlePremio -->> UIPremio: Mensagem de dados inválidos
UIPremio -> ControlePremio: cadPremio(premio)
end

ControlePremio -->> Premio **: <<create>>
Premio -->> ControlePremio: Prêmio criado
ControlePremio -->> UIPremio --: Mensagem de confirmação

@enduml