@startuml DiagramaEditarPremio
title "Diagrama de Sequência: Editação de Prêmio"
hide footbox

actor "Pesquisador" as Pesquisador
boundary "Tela de Prêmio" as UIPremio
control "Controle de Prêmio" as ControlePremio
entity "Prêmio" as Premio

Pesquisador --> UIPremio ++: Solicita a edição

autonumber
UIPremio -> ControlePremio++: editPremio(premio)

group Enquanto os dados forem inválidos
ControlePremio -->> UIPremio: Mensagem de dados inválidos
UIPremio -> ControlePremio: editPremio(premio)
end

ControlePremio -->> Premio ++: <<edit>>
Premio -->> ControlePremio --: Prêmio editado
ControlePremio -->> UIPremio --: Mensagem de confirmação
autonumber stop
@enduml