@startuml DiagramaCadastrarProducaoBibliografica
title "Diagrama de Sequência: Cadastro de Produção Bibliográfica"
hide footbox

actor "Pesquisador" as Pesquisador
boundary "Tela de Produção Bibliográfica" as UIProducaoBibliografica
control "Controle de Produção Bibliográfica" as ControleProducaoBibliografica
entity "Produção Bibliográfica" as ProducaoBibliografica

Pesquisador -> UIProducaoBibliografica++: Solicita o cadastro

autonumber
UIProducaoBibliografica -> ControleProducaoBibliografica++: cadProdBib(prodBib)

group Enquanto os dados forem inválidos
ControleProducaoBibliografica -->> UIProducaoBibliografica: Mensagem de dados inválidos
UIProducaoBibliografica -> ControleProducaoBibliografica --: cadProdBib(prodBib)
end

ControleProducaoBibliografica -->> ProducaoBibliografica **: <<create>>
ProducaoBibliografica -->> ControleProducaoBibliografica: Produção Bibliográfica criada
ControleProducaoBibliografica -->> UIProducaoBibliografica --: Mensagem de confirmação
autonumber stop
@enduml