@startuml DiagramaEditarProducao
title "Diagrama de Sequência: Edição de Produção Bibliográfica"
hide footbox

actor "Pesquisador" as Pesquisador
boundary "Tela de Produção Bibliográfica" as UIEditarProducaoBibliografica
control "Controle de Produção de Bibliográfica" as ControleProducaoBibliografica
entity "Produção Bibliográfica" as ProducaoBibliografica

Pesquisador -> UIEditarProducaoBibliografica++: Solicita a edição
autonumber
UIEditarProducaoBibliografica -> ControleProducaoBibliografica++: editProdBib(prodBib)

group Enquanto os dados forem inválidos
ControleProducaoBibliografica -->> UIEditarProducaoBibliografica: Mensagem de dados inválidos
UIEditarProducaoBibliografica -> ControleProducaoBibliografica: editProdBib(prodBib)
end

ControleProducaoBibliografica -->> ProducaoBibliografica ++: <<edit>>
ProducaoBibliografica -->> ControleProducaoBibliografica --: Produção Bibliográfica editada
ControleProducaoBibliografica -->> UIEditarProducaoBibliografica --: Mensagem de confirmação
autonumber stop
@enduml