@startuml teste2
!include Diagramas/Projetos de Pesquisa/cabecalhoProjetosDePesquisa.wsd

title "Diagrama de Sequência: Edição de Projetos de Pesquisa"

pesq -> uiPP ++: Solicita a edição

autonumber
uiPP -> contPP ++: editProjPesq(projPesq)

group Enquanto os dados forem inválidos
contPP -->> uiPP: Mensagem de dados inválidos
uiPP -> contPP: editProjPesq(projPesq)
end

contPP -->> pp ++: <edit>

autonumber stop
pp -->> contPP --: Projeto de Pesquisa editado
contPP -->> uiPP --: Mensagem de confirmação
@enduml