@startuml diagSeqCadLinhasDePesquisa
!include %getenv("HOME")/Linhas de Pesquisa/cabecalhoLinhasDePesquisa.wsd

title "Diagrama de Sequência do Cadastro de Linhas de Pesquisa"

pesq -> uiLP ++: Preenche formulário
uiLP -> contLP ++: regLinhaPesquisa()
contLP -->> lp **: <<create>>
lp --> contLP : Linha de Pesquisa criada
contLP --> uiLP: Mensagem de confirmação

@enduml