@startuml diagSeqCadLinhasDePesquisa
!include Diagramas/Linhas de Pesquisa/cabecalhoLinhasDePesquisa.wsd

title "Diagrama de Sequência: Cadastro de Linhas de Pesquisa"

pesq -> uiLP ++: Solicita o cadastro

autonumber
uiLP -> contLP ++: cadLinhaPesquisa(linhaPesquisa)

group Enquanto os dados forem inválidos
contLP -->> uiLP: Mensagem de dados inválidos
uiLP -> contLP: cadLinhaPesquisa(linhaPesquisa)
end

contLP -->> lp **: <<create>>

lp -->> contLP: Linha de Pesquisa criada
contLP -->> uiLP --: Mensagem de confirmação

@enduml