# Generated by Django 3.0.3 on 2023-01-29 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LinhasDePesquisa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('detalhamento', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='ProjetosDePesquisa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('integrantes', models.CharField(max_length=200)),
                ('anoDeInicio', models.IntegerField()),
                ('anoDeTermino', models.IntegerField()),
                ('titulo', models.CharField(max_length=200)),
                ('descricao', models.TextField()),
            ],
        ),
    ]
