@startuml diaSeqCadastrarResumo
title "Diagrama de Sequência: Cadastro do resumo"
hide footbox

actor Pesquisador as user
boundary "Tela do Currículo" as uiRE 
control "Controle de Currículo" as contRE 
entity "Currículo" as re 

user -> uiRE ++: Solicita o cadastro

autonumber
uiRE -> contRE ++: cadResumo(resumo)

group Enquanto os dados forem inválidos
contRE -->> uiRE: Mensagem de dados inválidos
uiRE -> contRE: cadResumo(resumo)
end

contRE -> re ++: setResumo(resumo)

re -->> contRE --: Resumo cadastrado
contRE -->> uiRE --: Mensagem de confirmação

@enduml