@startuml diaSeqEditarResumo
title "Diagrama de Sequência: Edição do Resumo"
hide footbox

actor Pesquisador as user
boundary "Tela do Currículo" as uiRE 
control "Controle do Currículo" as contRE 
entity "Currículo" as res

user -> uiRE ++: Solicita a edição

autonumber
uiRE -> contRE ++: editResumo(resumo)

group Enquanto os dados forem inválidos
contRE -->> uiRE: Mensagem de dados inválidos
uiRE -> contRE: editResumo(resumo)
end

contRE -> res ++: setResumo(resumo)

autonumber stop
res -->> contRE --: Resumo editado
contRE -->> uiRE --: Mensagem de confirmação

@enduml