@startuml   diagramaAtividade

    title "Diagrama de Atividades: Edição de Formação Acadêmica"

    start
    :Acessa edição de formação acadêmica;
    :Exibir formulário de formação acadêmica;
    if (Tipo de formação) then (Graduação)
    	:Preencher formulário de Graduação;
		:Soliciar edição;
		stop
    else (Pós-Graduação)
    	:Preencher formulário de Pós-Graduação;
		:Soliciar edição;
		stop
    endif
@enduml 
