@startuml "metodos"
skinparam classAttributeIconSize 0
class "Curriculo" {
	+setResumo(String: resumo): void
	+gerarCurriculo(): void
}
class "CtrlCurriculo" {
	+cadResumo(String: resumo): bool
	+editResumo(String: resumo): bool
}
class "CurriculoUI" {
}
class "Pesquisador"{
}
class "EnderecoProfissional" {
}
class "CtrlPesquisador" {
}
class "PesquisadorUI" {
}
class "AtuacaoProfissional" {
}
class "CtrlAtuacaoProfissional" {
	+cadAtuacaoProf(AtuacaoProfissional: atuacaoProf): bool
	+editAtuacaoProf(AtuacaoProfissional: atuacaoProf): bool
}
class "AtuacaoProfissionalUI" {
}
class "FormacaoAcademica" {
}
class "Graduacao" {
}
class "PosGraducao" {
}
class "AreaDePesquisa" {
}
class "CtrlFormacaoAcademica" {
	+cadGrad(Graduacao: grad): bool
	+editGrad(Graduacao: grad): bool
	+cadPosGrad(PosGraducao: posGrad): bool
	+editPosGrad(PosGraducao: posGrad): bool
	+cadAreaPesq(AreaDePesquisa: areaPesq): bool
	+editAreaPesq(AreaDePesquisa: areaPesq): bool
}
class "FormacaoAcademicaUI" {
	-formGrad(): void
	-formPosGrad(): void
}
class "OrientacaoAcademica" {
}
class "CtrlOrientacaoAcademica" {
}
class "OrientacaoAcademicaUI" {
}
class "ProducaoTecnica" {
}
class "CtrlProducaoTecnica" {
	+cadProdTec(ProducaoTecnica: prodTec): bool
	+editProdTec(ProducaoTecnica: prodTec): bool
}
class "ProducaoTecnicaUI" {
}
class "ProficienciaIdioma" {
}
class "CtrlProficienciaIdioma" {
	+cadProfIdioma(ProficienciaIdioma: profIdioma): bool
	+editProfIdioma(ProficienciaIdioma: profIdioma): bool
}
class "ProficienciaIdiomaUI" {
}
class "ProducaoBibliografica" {
}
class "CtrlProducaoBibliografica" {
	+cadProdBib(ProducaoBibliografica: prodBib): bool
	+editProdBib(ProducaoBibliografica: prodBib): bool
}
class "ProducaoBibliograficaUI" {
}
class "LinhaDePesquisa" {
}
class "CtrlLinhaDePesquisa" {
	+cadLinhaPesquisa(LinhaDePesquisa: LinhaDePesquisa): bool
	+editLinhaPesquisa(LinhaDePesquisa: linhaPesquisa): bool
}
class "LinhaDePesquisaUI" {
}
class "Premio" {
}
class "CtrlPremio" {
	+cadPremio(Premio: premio): bool
	+editPremio(Premio: premio): bool
}
class "PremioUI" {
}
class "ProjetoDePesquisa" {
}
class "CtrlProjetoDePesquisa" {
	+cadProjPesq(ProjetoDePesquisa: projPesq): bool
	+editProjPesq(ProjetoDePesquisa: projPesq): bool
}
class "ProjetoDePesquisaUI" {
}
@enduml