@startuml DiagramaCadastrarIdioma
title "Diagrama de Sequência: Cadastro de Proficiência em Idioma"
hide footbox

actor "Pesquisador" as Pesquisador
boundary "Tela de Proficiência em Idioma" as UIProficienciaIdioma
control "Controle de Proficiencia em Idioma" as ControleProficienciaIdioma
entity "Proficiencia em Idioma" as ProficienciaIdioma

Pesquisador -> UIProficienciaIdioma++: Solicita o cadastro

autonumber
UIProficienciaIdioma -> ControleProficienciaIdioma++: cadProfIdioma(profIdioma)

group Enquanto os dados forem inválidos
ControleProficienciaIdioma -->> UIProficienciaIdioma: Mensagem de dados inválidos
UIProficienciaIdioma -> ControleProficienciaIdioma: cadProfIdioma(profIdioma)
end

ControleProficienciaIdioma -->> ProficienciaIdioma **: <<create>>
ProficienciaIdioma -->> ControleProficienciaIdioma: Proficiência em idioma criada
ControleProficienciaIdioma -->> UIProficienciaIdioma --: Mensagem de confirmação
autonumber stop
@enduml