# Generated by Django 4.1.5 on 2023-03-26 17:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AreaPesquisa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area', models.CharField(max_length=200)),
                ('grande_area', models.CharField(max_length=200)),
                ('sub_area', models.CharField(max_length=200)),
                ('especialidade_area', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='AtuacaoProfissional',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ano_inicio', models.IntegerField()),
                ('ano_termino', models.IntegerField()),
                ('instituicao', models.CharField(max_length=300)),
                ('vinculo', models.CharField(max_length=100)),
                ('enquad_profissional', models.CharField(max_length=200)),
                ('regime', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='EnderecoProfissional',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logradouro', models.CharField(max_length=200)),
                ('bairro', models.CharField(max_length=100)),
                ('cidade', models.CharField(max_length=100)),
                ('estado', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Graduacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('orientador', models.CharField(max_length=200)),
                ('notaConclusao', models.FloatField()),
                ('palavrasChave', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='LinhaPesquisa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('detalhamento', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='OrientacaoAcademica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orientando', models.CharField(max_length=200)),
                ('tipo', models.IntegerField()),
                ('instituicao', models.CharField(max_length=300)),
                ('descricao', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Premio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ano', models.IntegerField()),
                ('descricao', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='ProducaoBibliografica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=300)),
                ('autores', models.TextField()),
                ('pagina_inicial', models.IntegerField()),
                ('pagina_final', models.IntegerField()),
                ('edicao', models.CharField(max_length=100)),
                ('ano', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='ProducaoTecnica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=300)),
                ('autores', models.TextField()),
                ('ano', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='ProeficienciaIdioma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idioma', models.CharField(max_length=100)),
                ('compreensao', models.IntegerField()),
                ('fala', models.IntegerField()),
                ('escrita', models.IntegerField()),
                ('leitura', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='ProjetoPesquisa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('integrantes', models.TextField()),
                ('titulo', models.CharField(max_length=200)),
                ('ano_inicio', models.IntegerField()),
                ('ano_termino', models.IntegerField()),
                ('descricao', models.TextField()),
                ('situacao', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='PosGraduacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('orientador', models.CharField(max_length=200)),
                ('palavrasChave', models.CharField(max_length=500)),
                ('area_pesquisa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='curriculo.areapesquisa')),
            ],
        ),
        migrations.CreateModel(
            name='Pesquisador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('cpf', models.CharField(max_length=11)),
                ('email', models.EmailField(max_length=254)),
                ('imagem', models.TextField()),
                ('endereco', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='curriculo.enderecoprofissional')),
            ],
        ),
        migrations.CreateModel(
            name='Curriculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('atuacoes_profissionais', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='curriculo.atuacaoprofissional')),
                ('graduacoes', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='curriculo.graduacao')),
                ('orientacoesAcademicas', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='curriculo.orientacaoacademica')),
                ('pesquisador', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='curriculo.pesquisador')),
                ('pos_graduacoes', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='curriculo.posgraduacao')),
                ('premios', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='curriculo.premio')),
                ('producoesBibliograficas', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='curriculo.producaobibliografica')),
                ('producoesTecnicas', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='curriculo.producaotecnica')),
                ('proficienciaIdiomas', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='curriculo.proeficienciaidioma')),
                ('projeto_pesquisa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='curriculo.projetopesquisa')),
            ],
        ),
    ]
