# Generated by Django 4.1.5 on 2023-04-22 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curriculo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='linhapesquisa',
            name='detalhamento',
            field=models.CharField(max_length=150),
        ),
    ]
