# Generated by Django 4.1.5 on 2023-03-26 21:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('curriculo', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pesquisador',
            old_name='imagem',
            new_name='foto',
        ),
    ]
