# Generated by Django 4.1.5 on 2023-04-23 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curriculo', '0002_alter_posgraduacao_area_de_pesquisa'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='posgraduacao',
            name='area_de_pesquisa',
        ),
        migrations.AddField(
            model_name='posgraduacao',
            name='area',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='posgraduacao',
            name='especialidade_area',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='posgraduacao',
            name='grande_area',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='posgraduacao',
            name='sub_area',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.DeleteModel(
            name='AreaPesquisa',
        ),
    ]
