# Generated by Django 4.1.5 on 2023-04-22 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curriculo', '0002_alter_linhapesquisa_detalhamento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proeficienciaidioma',
            name='compreensao',
            field=models.IntegerField(choices=[(0, 'Pouco'), (1, 'Razoavelmente'), (2, 'Bem')]),
        ),
    ]
