# Generated by Django 4.1.5 on 2023-04-24 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curriculo', '0005_alter_pesquisador_foto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='atuacaoprofissional',
            name='ano_de_inicio',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='atuacaoprofissional',
            name='ano_de_termino',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='atuacaoprofissional',
            name='enquad_profissional',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='atuacaoprofissional',
            name='instituicao',
            field=models.CharField(default='', max_length=300),
        ),
        migrations.AlterField(
            model_name='atuacaoprofissional',
            name='regime',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='atuacaoprofissional',
            name='vinculo',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='projetopesquisa',
            name='ano_de_inicio',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='projetopesquisa',
            name='ano_de_termino',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='projetopesquisa',
            name='descricao',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='projetopesquisa',
            name='integrantes',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='projetopesquisa',
            name='situacao',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='projetopesquisa',
            name='titulo',
            field=models.CharField(default='', max_length=200),
        ),
    ]
